name: Test
on: [push, pull_request]
jobs:
  Assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build project
        run: ./gradlew clean build
